config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :activity_logs, only: :index
  end

  namespace :api, defaults: { format: :json } do
    resources :activities, only: :index
    resources :activity_logs, only: [:create, :update]
    resources :babies, only: :index do
      resources :activity_logs, only: :index
    end
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :activity_logs
end

app/models/activity_log.rb
class ActivityLog < ApplicationRecord
  ACTIVITY_LOG_STATUSES = { done: 'Termiando', in_progress: 'En progreso' }.freeze
  belongs_to :baby
  belongs_to :assistant
  belongs_to :activity

  validate :validate_stop_time
  validates :baby, :assistant, :activity, presence: true

  before_save :set_duration

  scope :by_baby_id, ->(baby_id) { where(baby_id: baby_id) }
  scope :by_assistant_id, ->(assistant_id) { where(assistant_id: assistant_id) }
  scope :finished, -> { where.not(stop_time: nil) }
  scope :in_progress, -> { where(stop_time: nil) }

  def self.by_status(status)
    status = status.to_sym

    return none unless ACTIVITY_LOG_STATUSES.keys.include?(status)

    status == :done ? finished : in_progress
  end

  def status
    set_duration

    duration.present? ? 'Terminado' : 'En progreso'
  end

  private

  def set_duration
    self.duration = (stop_time - start_time) / 1.minute if stop_time.present? && start_time.present?
  end

  def validate_stop_time
    if start_time.present? && stop_time.present? && stop_time <= start_time
      errors.add(:stop_time, 'The activity can\'t finish before start time')
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assistant.rb
class Assistant < ApplicationRecord
  has_many :activity_logs
end

app/models/baby.rb
class Baby < ApplicationRecord
  has_many :activity_logs

  def age_in_months
    today = Time.current

    (today.year * 12 + today.month) - (birthday.year * 12 + birthday.month)
  end
end

app/controllers/admin/activity_logs_controller.rb
class Admin::ActivityLogsController < ApplicationController
  ITERABLE_KEY_PARAMS = %w[baby_id assistant_id]

  def index
    @babies = Baby.pluck(:name, :id)
    @assistants = Assistant.pluck(:name, :id)
    @status = ActivityLog::ACTIVITY_LOG_STATUSES.map { |key, value| [value, key] }
    @activity_logs = filtered_activity_logs
  end
end

private

def filtered_activity_logs
  activity_logs = ActivityLog.joins(:baby, :assistant, :activity)

  permitted_params.each do |param_key, param_value|
    if param_value.present? && Admin::ActivityLogsController::ITERABLE_KEY_PARAMS.include?(param_key)
      activity_logs = activity_logs.send("by_#{param_key}", param_value)
    end
  end

  activity_logs = activity_logs.by_status(permitted_params[:status]) if permitted_params[:status].present?

  activity_logs.select('activity_logs.*, babies.name AS baby_name, assistants.name AS assistant_name, activities.name AS activity_name')
end

def permitted_params
  params.permit(:baby_id, :assistant_id, :status)
end

app/controllers/api/activities_controller.rb
class Api::ActivitiesController < Api::ApiController
  def index
    # Maybe add pagination here but would increase the scope of the exercise
    render json: ActivitySerializer.new(Activity.all, is_collection: true).serialized_json
  end
end

app/controllers/api/activity_logs_controller.rb
class Api::ActivityLogsController < Api::ApiController
  def index
    baby_id = params[:baby_id]
    if baby_id.present?
      render json: ActivityLogWithAssistentNameSerializer.new(ActivityLog.by_baby_id(baby_id), is_collection: true).serialized_json
    else
      render json: []
    end
  end

  def create
    new_activity_log = ActivityLog.create(permitted_params)
    if new_activity_log.save
      render json: ActivityLogSerializer.new(new_activity_log, is_collection: false).serialized_json, status: :created
    else
      render json: new_activity_log.errors.messages.as_json, status: :unprocessable_entity
    end
  end

  def update
    activity_log = ActivityLog.find_by(id: params[:id])

    if !activity_log.present?
      render json: { error: 'Item not found' }, status: 404
    elsif activity_log.update(permitted_params)
      render json: ActivityLogSerializer.new(activity_log, is_collection: false).serialized_json
    else
      render json: activity_log.error.messages, status: :unprocessable_entity
    end
  end

  private

  def permitted_params
    params
      .require(:activity_log)
      .permit(
    :id,
          :start_time,
          :stop_time,
          :comments,
          :baby_id,
          :assistant_id,
          :activity_id
      )
  end
end

app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController
  skip_before_action :verify_authenticity_token
end

app/controllers/api/babies_controller.rb
class Api::BabiesController < Api::ApiController
  def index
    # Maybe add pagination here but would increase the scope of the exercise
    render json: BabySerializer.new(Baby.all).serialized_json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/activity_logs_helper.rb
# frozen_string_literal: true

module Admin::ActivityLogsHelper
  def date_in_monterrey_timezone(datetime)
    datetime.in_time_zone('America/Monterrey')
  end

  def duration_or_empty(duration)
    duration.present? ? duration : '*'
  end
end

app/views/admin/activity_logs/index.html.erb
<%= form_tag(admin_activity_logs_path, method: 'get') do%>
  <div class="form-row mb-4 mt-4">
    <div class="col">
      <%= select_tag(
            'baby_id',
            options_for_select(@babies, permitted_params[:baby]),
            include_blank: 'Seleccionar bebé',
            class: 'form-control')
      %>
    </div>
    <div class="col">
      <%= select_tag(
            'assistant_id',
            options_for_select(@assistants, permitted_params[:assistant]),
            include_blank: 'Seleccionar asistente',
            class: 'form-control')
      %>
    </div>
    <div class="col">
      <%= select_tag(
            'status',
            options_for_select(@status, permitted_params[:status]),
            include_blank: 'Todos',
            class: 'form-control')
      %>
    </div>
    <div class="col">
      <button type="submit" class="btn btn-primary">Filtrar</button>
    </div>
  </div>
<% end %>

<table class="table table-hover">
  <thead>
  <tr>
    <th scope="col">Bebé</th>
    <th scope="col">Asistente</th>
    <th scope="col">Actividad</th>
    <th scope="col">Inicio</th>
    <th scope="col">Estatus</th>
    <th scope="col">Duración</th>
  </tr>
  </thead>
  <tbody>
  <% @activity_logs.each do |activity_log| %>
    <tr>
      <td><%= activity_log.baby_name %></td>
      <td><%= activity_log.assistant_name %></td>
      <td><%= activity_log.activity_name %></td>
      <td><%= date_in_monterrey_timezone(activity_log.start_time) %></td>
      <td><%= activity_log.status %></td>
      <td><%= duration_or_empty(activity_log.duration) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KineduLab</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>